### ISSUE TITLE
Put templates in a directory

### ISSUE THREAD

**Issue by Abhishek-kumar09** [layer5labs/meshmap-snapshot#26]
Templates: https://github.com/layer5labs/meshmap-snapshot/pull/25

**Comment by suhail34** [comment]
Hi , in github workflow directory? I will do that

**Comment by Abhishek-kumar09** [comment]
no, create a new folder in the root directory and we have to put the templates there. The templates are later referenced by meshery-cloud, which is out of scope of this issue.
