### ISSUE TITLE
Add the .github workflows and templates from meshery/meshery

### ISSUE THREAD

**Issue by Abhishek-kumar09** [layer5labs/meshmap-snapshot#29]
Get the list of most recent templates, PR body, issue body, release drafts etc from the [meshery/meshery](https://github.com/meshery/meshery/tree/master/.github)

**Comment by ShivangRawat30** [comment]
can you assign this to me ?

**Comment by Abhishek-kumar09** [comment]
Sure @ShivangRawat30, go ahead.
