### ISSUE TITLE
Update the PR-target test to incorporate new release changes/format.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [layer5labs/meshmap-snapshot#32]
**Describe the bug**
Update [pr-target-test.yml](https://github.com/layer5labs/meshmap-snapshot/blob/master/.github/workflows/pr-target-test.yml) to use the [latest action pattern](https://github.com/layer5labs/meshmap-snapshot#when-infrastructure-is-identified-via-url)

**Comment by Meyazhagan** [comment]
@Abhishek-kumar09 Shall I try!

**Comment by Abhishek-kumar09** [comment]
Yes, please. The working actions are depicted in the readme.MD
