### ISSUE TITLE
Workflow failure due to `/` used in relative application path

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshmap-snapshot#68]
**Describe the bug**

```
[Invalid workflow file: .github/workflows/meshmap.yml#L46](https://github.com/meshery/meshery/actions/runs/7255261582/workflow)
The workflow is not valid. .github/workflows/meshmap.yml (Line: 46, Col: 21): Unexpected symbol: '/tree/master/install/deployment_yamls/k8s'. Located at position 26 within expression: inputs.fileName == '' && /tree/master/install/deployment_yamls/k8s || inputs.fileName
```

Example - https://github.com/meshery/meshery/actions/runs/7255261582/workflow

This needs to be fixed not in the workflow, but in the configuration wizard / action.

**Comment by leecalcote** [comment]
As a temp fix, I removed the `/`, however, this needs fixed in the action / in the configuration flow.

Also, the configuration wizard forces the user to allow the bot to auto create and commit the meshmap.yaml workflow and doesn't allow them to create the workflow themselves.

**Comment by leecalcote** [comment]
Still failing - https://github.com/meshery/meshery/actions/runs/7255149001/job/19765194751

**Comment by RipulHandoo** [comment]
@leecalcote Sir, I think this issue has been addressed. [Here](https://github.com/meshery/meshery/blob/master/.github/workflows/meshmap.yml#L46) is the corrected solution.

**Comment by leecalcote** [comment]
Thanks for this, @RipulHandoo
